/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/assets/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get an Asset
     * @description Image typed files can be dynamically resized and transformed to fit any need.
     */
    get: operations['getAsset'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Retrieve a Temporary Access Token
     * @description Retrieve a Temporary Access Token
     */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh Token
     * @description Refresh a Temporary Access Token.
     */
    post: operations['refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Log Out
     * @description Log Out
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/password/request': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request a Password Reset
     * @description Request a reset password email to be send.
     */
    post: operations['passwordRequest'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/password/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset a Password
     * @description The request a password reset endpoint sends an email with a link to the admin app which in turn uses this endpoint to allow the user to reset their password.
     */
    post: operations['passwordReset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/oauth': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List OAuth Providers
     * @description List configured OAuth providers.
     */
    get: operations['oauth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/oauth/{provider}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Authenticated using an OAuth provider
     * @description Start OAuth flow using the specified provider
     */
    get: operations['oauthProvider'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/server/info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * System Info
     * @description Perform a system status check and return the options.
     */
    get: operations['serverInfo'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/server/ping': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ping
     * @description Ping, pong. Ping.. pong.
     */
    get: operations['ping'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/utils/hash/generate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Hash a string
     * @description Generate a hash for a given string.
     */
    post: operations['hash-generate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/utils/hash/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Hash a string
     * @description Generate a hash for a given string.
     */
    post: operations['hash-verify'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/utils/sort/{collection}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sort Items
     * @description Re-sort items in collection based on start and to value of item
     */
    post: operations['sort'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/utils/import/{collection}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Import Items
     * @description Import multiple records from a JSON or CSV file into a collection.
     */
    post: operations['import'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/utils/export/{collection}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Export Items
     * @description Export a larger data set to a file in the File Library
     */
    post: operations['export'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/utils/cache/clear': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Clear Cache
     * @description Resets both the data and schema cache of Directus.
     */
    post: operations['clear-cache'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/utils/random/string': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a Random String
     * @description Returns a random string of given length.
     */
    get: operations['random'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/items/dora_world_contents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Items
     * @description List the dora_world_contents items.
     */
    get: operations['readItemsDoraWorldContents'];
    put?: never;
    /**
     * Create an Item
     * @description Create a new dora_world_contents item.
     */
    post: operations['createItemsDoraWorldContents'];
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Multiple Items
     * @description Update multiple dora_world_contents items at the same time.
     */
    patch: operations['updateItemsDoraWorldContents'];
    trace?: never;
  };
  '/items/dora_world_contents/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve an Item
     * @description Retrieve a single dora_world_contents item by unique identifier.
     */
    get: operations['readSingleItemsDoraWorldContents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update an Item
     * @description Update an existing dora_world_contents item.
     */
    patch: operations['updateSingleItemsDoraWorldContents'];
    trace?: never;
  };
  '/items/languages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Items
     * @description List the languages items.
     */
    get: operations['readItemsLanguages'];
    put?: never;
    /**
     * Create an Item
     * @description Create a new languages item.
     */
    post: operations['createItemsLanguages'];
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Multiple Items
     * @description Update multiple languages items at the same time.
     */
    patch: operations['updateItemsLanguages'];
    trace?: never;
  };
  '/items/languages/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve an Item
     * @description Retrieve a single languages item by unique identifier.
     */
    get: operations['readSingleItemsLanguages'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update an Item
     * @description Update an existing languages item.
     */
    patch: operations['updateSingleItemsLanguages'];
    trace?: never;
  };
  '/items/dora_world_contents_translations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Items
     * @description List the dora_world_contents_translations items.
     */
    get: operations['readItemsDoraWorldContentsTranslations'];
    put?: never;
    /**
     * Create an Item
     * @description Create a new dora_world_contents_translations item.
     */
    post: operations['createItemsDoraWorldContentsTranslations'];
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Multiple Items
     * @description Update multiple dora_world_contents_translations items at the same time.
     */
    patch: operations['updateItemsDoraWorldContentsTranslations'];
    trace?: never;
  };
  '/items/dora_world_contents_translations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve an Item
     * @description Retrieve a single dora_world_contents_translations item by unique identifier.
     */
    get: operations['readSingleItemsDoraWorldContentsTranslations'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update an Item
     * @description Update an existing dora_world_contents_translations item.
     */
    patch: operations['updateSingleItemsDoraWorldContentsTranslations'];
    trace?: never;
  };
  '/items/fujiko_museum_contents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Items
     * @description List the fujiko_museum_contents items.
     */
    get: operations['readItemsFujikoMuseumContents'];
    put?: never;
    /**
     * Create an Item
     * @description Create a new fujiko_museum_contents item.
     */
    post: operations['createItemsFujikoMuseumContents'];
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Multiple Items
     * @description Update multiple fujiko_museum_contents items at the same time.
     */
    patch: operations['updateItemsFujikoMuseumContents'];
    trace?: never;
  };
  '/items/fujiko_museum_contents/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve an Item
     * @description Retrieve a single fujiko_museum_contents item by unique identifier.
     */
    get: operations['readSingleItemsFujikoMuseumContents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update an Item
     * @description Update an existing fujiko_museum_contents item.
     */
    patch: operations['updateSingleItemsFujikoMuseumContents'];
    trace?: never;
  };
  '/items/fujiko_museum_contents_translations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Items
     * @description List the fujiko_museum_contents_translations items.
     */
    get: operations['readItemsFujikoMuseumContentsTranslations'];
    put?: never;
    /**
     * Create an Item
     * @description Create a new fujiko_museum_contents_translations item.
     */
    post: operations['createItemsFujikoMuseumContentsTranslations'];
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Multiple Items
     * @description Update multiple fujiko_museum_contents_translations items at the same time.
     */
    patch: operations['updateItemsFujikoMuseumContentsTranslations'];
    trace?: never;
  };
  '/items/fujiko_museum_contents_translations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve an Item
     * @description Retrieve a single fujiko_museum_contents_translations item by unique identifier.
     */
    get: operations['readSingleItemsFujikoMuseumContentsTranslations'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update an Item
     * @description Update an existing fujiko_museum_contents_translations item.
     */
    patch: operations['updateSingleItemsFujikoMuseumContentsTranslations'];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Files: {
      /**
       * @description Unique identifier for the file.
       * @example 8cbb43fe-4cdf-4991-8352-c461779cec02
       */
      id?: string;
      /**
       * @description Where the file is stored. Either `local` for the local filesystem or the name of the storage adapter (for example `s3`).
       * @example local
       */
      storage?: string;
      /**
       * @description Name of the file on disk. By default, Directus uses a random hash for the filename.
       * @example a88c3b72-ac58-5436-a4ec-b2858531333a.jpg
       */
      filename_disk?: string;
      /**
       * @description How you want to the file to be named when it's being downloaded.
       * @example avatar.jpg
       */
      filename_download?: string;
      /**
       * @description Title for the file. Is extracted from the filename on upload, but can be edited by the user.
       * @example User Avatar
       */
      title?: string;
      /**
       * @description MIME type of the file.
       * @example image/jpeg
       */
      type?: string;
      /**
       * @description Virtual folder where this file resides in.
       * @example null
       */
      folder?: (string | components['schemas']['Folders']) | null;
      /**
       * Format: date-time
       * @description When the file was created.
       * @example 2019-12-03T00:10:15+00:00
       */
      created_on?: string;
      /**
       * @description Who uploaded the file.
       * @example 63716273-0f29-4648-8a2a-2af2948f6f78
       */
      uploaded_by?: string | components['schemas']['Users'];
      /**
       * Format: date-time
       * @description When the file was last uploaded/replaced.
       * @example 2019-12-03T00:10:15+00:00
       */
      uploaded_on?: string;
      /**
       * @description Character set of the file.
       * @example binary
       */
      charset?: string | null;
      /**
       * @description Size of the file in bytes.
       * @example 137862
       */
      filesize?: number;
      /**
       * @description Width of the file in pixels. Only applies to images.
       * @example 800
       */
      width?: number | null;
      /**
       * @description Height of the file in pixels. Only applies to images.
       * @example 838
       */
      height?: number | null;
      /**
       * @description Duration of the file in seconds. Only applies to audio and video.
       * @example 0
       */
      duration?: number | null;
      /**
       * @description Where the file was embedded from.
       * @example null
       */
      embed?: string | null;
      /** @description Description for the file. */
      description?: string | null;
      /** @description Where the file was created. Is automatically populated based on Exif data for images. */
      location?: string | null;
      /** @description Tags for the file. Is automatically populated based on Exif data for images. */
      tags?: string[] | null;
      /** @description IPTC, Exif, and ICC metadata extracted from file */
      metadata?: Record<string, never> | null;
    };
    Folders: {
      /**
       * @description Unique identifier for the folder.
       * @example 0cf0e03d-4364-45df-b77b-ca61f61869d2
       */
      id?: string;
      /**
       * @description Name of the folder.
       * @example New York
       */
      name?: string;
      /**
       * @description Unique identifier of the parent folder. This allows for nested folders.
       * @example null
       */
      parent?: (string | components['schemas']['Folders']) | null;
    };
    Roles: {
      /**
       * @description Unique identifier for the role.
       * @example 2f24211d-d928-469a-aea3-3c8f53d4e426
       */
      id?: string;
      /**
       * @description Name of the role.
       * @example Administrator
       */
      name?: string;
      /**
       * @description The role's icon.
       * @example verified_user
       */
      icon?: string;
      /**
       * @description Description of the role.
       * @example Admins have access to all managed data within the system by default
       */
      description?: string | null;
      /**
       * @description Array of IP addresses that are allowed to connect to the API as a user of this role.
       * @example []
       */
      ip_access?: string[];
      /**
       * @description Whether or not this role enforces the use of 2FA.
       * @example false
       */
      enforce_tfa?: boolean;
      /**
       * @description Admin role. If true, skips all permission checks.
       * @example false
       */
      admin_access?: boolean;
      /**
       * @description The users in the role are allowed to use the app.
       * @example true
       */
      app_access?: boolean;
    };
    Users: {
      /**
       * @description Unique identifier for the user.
       * @example 63716273-0f29-4648-8a2a-2af2948f6f78
       */
      id?: string;
      /**
       * @description First name of the user.
       * @example Admin
       */
      first_name?: string;
      /**
       * @description Last name of the user.
       * @example User
       */
      last_name?: string;
      /**
       * Format: email
       * @description Unique email address for the user.
       * @example admin@example.com
       */
      email?: string;
      /** @description Password of the user. */
      password?: string;
      /**
       * @description The user's location.
       * @example null
       */
      location?: string | null;
      /**
       * @description The user's title.
       * @example null
       */
      title?: string | null;
      /**
       * @description The user's description.
       * @example null
       */
      description?: string | null;
      /**
       * @description The user's tags.
       * @example null
       */
      tags?: string[] | null;
      /**
       * @description The user's avatar.
       * @example null
       */
      avatar?: (string | components['schemas']['Files']) | null;
      /**
       * @description The user's language used in Directus.
       * @example en-US
       */
      language?: string;
      /**
       * @description What theme the user is using.
       * @example auto
       * @enum {string}
       */
      theme?: 'light' | 'dark' | 'auto';
      /**
       * @description The 2FA secret string that's used to generate one time passwords.
       * @example null
       */
      tfa_secret?: string | null;
      /**
       * @description Status of the user.
       * @example active
       * @enum {string}
       */
      status?: 'active' | 'invited' | 'draft' | 'suspended' | 'deleted';
      /**
       * @description Unique identifier of the role of this user.
       * @example 2f24211d-d928-469a-aea3-3c8f53d4e426
       */
      role?: string | components['schemas']['Roles'];
      /** @description Static token for the user. */
      token?: string | null;
      /**
       * Format: date-time
       * @description When this user used the API last.
       * @example 2020-05-31T14:32:37Z
       */
      last_access?: string | null;
      /**
       * @description Last page that the user was on.
       * @example /my-project/settings/collections/a
       */
      last_page?: string | null;
    };
    Query: {
      /**
       * @description Control what fields are being returned in the object.
       * @example [
       *       "*",
       *       "*.*"
       *     ]
       */
      fields?: string[];
      /**
       * @example {
       *       "<field>": {
       *         "<operator>": "<value>"
       *       }
       *     }
       */
      filter?: Record<string, never>;
      /** @description Filter by items that contain the given search query in one of their fields. */
      search?: string;
      /**
       * @description How to sort the returned items.
       * @example [
       *       "-date_created"
       *     ]
       */
      sort?: string[];
      /** @description Set the maximum number of items that will be returned */
      limit?: number;
      /** @description How many items to skip when fetching data. */
      offset?: number;
      /** @description Cursor for use in pagination. Often used in combination with limit. */
      page?: number;
      /**
       * @description Deep allows you to set any of the other query parameters on a nested relational dataset.
       * @example {
       *       "related_articles": {
       *         "_limit": 3
       *       }
       *     }
       */
      deep?: Record<string, never>;
    };
    'x-metadata': {
      /** @description Returns the total item count of the collection you're querying. */
      total_count?: number;
      /** @description Returns the item count of the collection you're querying, taking the current filter/search parameters into account. */
      filter_count?: number;
    };
    ItemsDoraWorldContents: {
      id: string;
      status?: string;
      sort?: number | null;
      /** Format: timestamp */
      date_created?: string | null;
      /** Format: timestamp */
      date_updated?: string | null;
      translations?:
        | (
            | number
            | components['schemas']['ItemsDoraWorldContentsTranslations']
          )[]
        | null;
    };
    ItemsLanguages: {
      code: string;
      name?: string | null;
      direction?: string | null;
    };
    ItemsDoraWorldContentsTranslations: {
      id?: number;
      dora_world_contents_id?:
        | (string | components['schemas']['ItemsDoraWorldContents'])
        | null;
      languages_code?:
        | (string | components['schemas']['ItemsLanguages'])
        | null;
    };
    ItemsFujikoMuseumContents: {
      id: string;
      status?: string;
      sort?: number | null;
      /** Format: timestamp */
      date_created?: string | null;
      /** Format: timestamp */
      date_updated?: string | null;
      translations?:
        | (
            | number
            | components['schemas']['ItemsFujikoMuseumContentsTranslations']
          )[]
        | null;
    };
    ItemsFujikoMuseumContentsTranslations: {
      id?: number;
      fujiko_museum_contents_id?:
        | (string | components['schemas']['ItemsFujikoMuseumContents'])
        | null;
      languages_code?:
        | (string | components['schemas']['ItemsLanguages'])
        | null;
    };
  };
  responses: {
    /** @description Error: Not found. */
    NotFoundError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          error?: {
            /** Format: int64 */
            code?: number;
            message?: string;
          };
        };
      };
    };
    /** @description Error: Unauthorized request */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          error?: {
            /** Format: int64 */
            code?: number;
            message?: string;
          };
        };
      };
    };
  };
  parameters: {
    /** @description Index */
    Id: number;
    /** @description Unique identifier for the object. */
    UUId: string;
    /** @description Collection of which you want to retrieve the items from. */
    Collection: string;
    /** @description Filter by items that contain the given search query in one of their fields. */
    Search: string;
    /** @description Cursor for use in pagination. Often used in combination with limit. */
    Page: number;
    /** @description How many items to skip when fetching data. */
    Offset: number;
    /** @description How to sort the returned items. `sort` is a CSV of fields used to sort the fetched items. Sorting defaults to ascending (ASC) order but a minus sign (` - `) can be used to reverse this to descending (DESC) order. Fields are prioritized by their order in the CSV. You can also use a ` ? ` to sort randomly. */
    Sort: string[];
    /** @description What metadata to return in the response. */
    Meta: string;
    /** @description A limit on the number of objects that are returned. */
    Limit: number;
    /** @description Select items in collection by given conditions. */
    Filter: string;
    /** @description Control what fields are being returned in the object. */
    Fields: string[];
    /** @description Saves the API response to a file. Accepts one of "csv", "csv_utf8", "json", "xml", "yaml". */
    Export: 'csv' | 'csv_utf8' | 'json' | 'xml' | 'yaml';
    /** @description Retrieve an item's state from a specific Content Version. The value corresponds to the "key" of the Content Version. */
    Version: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getAsset: {
    parameters: {
      query?: {
        /** @description The key of the asset size configured in settings. */
        key?: string;
        /** @description A JSON array of image transformations */
        transforms?: string;
        /** @description Download the asset to your computer */
        download?: boolean;
      };
      header?: never;
      path: {
        /** @description The id of the file. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
      404: components['responses']['NotFoundError'];
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          /**
           * @description Email address of the user you're retrieving the access token for.
           * @example admin@example.com
           */
          email: string;
          /**
           * Format: password
           * @description Password of the user.
           * @example password
           */
          password: string;
          /**
           * @description Whether to retrieve the refresh token in the JSON response, or in a httpOnly cookie.
           * @default json
           * @enum {string}
           */
          mode?: 'json' | 'cookie' | 'session';
          /** @description The user's one-time-password (if MFA is enabled). */
          otp?: string;
        };
      };
    };
    responses: {
      /** @description Successful authentification */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: {
              /** @example eyJhbGciOiJI... */
              access_token?: string;
              /** @example 900 */
              expires?: number;
              /** @example yuOJkjdPXMd... */
              refresh_token?: string;
            };
          };
        };
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          /**
           * @description JWT access token you want to refresh. This token can't be expired.
           * @example eyJ0eXAiOiJKV...
           */
          refresh_token?: string;
          /**
           * @description Whether to submit and retrieve the refresh token in the JSON response, or in a httpOnly cookie.
           * @default json
           * @enum {string}
           */
          mode?: 'json' | 'cookie' | 'session';
        };
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: {
              /** @example eyJhbGciOiJI... */
              access_token?: string;
              /** @example 900 */
              expires?: number;
              /** @example Gy-caJMpmGTA... */
              refresh_token?: string;
            };
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          /**
           * @description The refresh token to invalidate. If you have the refresh token in a cookie through /auth/login, you don't have to submit it here.
           * @example eyJ0eXAiOiJKV...
           */
          refresh_token?: string;
          /**
           * @description Whether the refresh token is submitted in the JSON response, or in a httpOnly cookie.
           * @enum {string}
           */
          mode?: 'json' | 'cookie' | 'session';
        };
      };
    };
    responses: {
      /** @description Request successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  passwordRequest: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          /**
           * @description Email address of the user you're requesting a reset for.
           * @example admin@example.com
           */
          email: string;
        };
      };
    };
    responses: {
      401: components['responses']['UnauthorizedError'];
    };
  };
  passwordReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          /**
           * @description One-time use JWT token that is used to verify the user.
           * @example eyJ0eXAiOiJKV1Qi...
           */
          token: string;
          /**
           * Format: password
           * @description New password for the user.
           * @example password
           */
          password: string;
        };
      };
    };
    responses: {
      401: components['responses']['UnauthorizedError'];
    };
  };
  oauth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            public?: boolean;
            /**
             * @example [
             *       "github",
             *       "facebook"
             *     ]
             */
            data?: string[];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
    };
  };
  oauthProvider: {
    parameters: {
      query?: {
        /** @description Where to redirect on successful login.<br/>If set the authentication details are set inside cookies otherwise a JSON is returned. */
        redirect?: string;
      };
      header?: never;
      path: {
        /** @description Key of the activated OAuth provider. */
        provider: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            public?: boolean;
            data?: {
              token?: string;
            };
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
    };
  };
  serverInfo: {
    parameters: {
      query: {
        /** @description The first time you create a project, the provided token will be saved and required for subsequent project installs. It can also be found and configured in `/config/__api.json` on your server. */
        super_admin_token: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: Record<string, never>;
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
      404: components['responses']['NotFoundError'];
    };
  };
  ping: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/text': string;
        };
      };
    };
  };
  'hash-generate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          /** @description String to hash. */
          string: string;
        };
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example $argon2i$v=19$m=4096,t=3,p=1$pOyIa/zmRAjCVLb2f7kOyg$DasoO6LzMM+6iKfzCDq6JbsYsZWLSm33p7i9NxL9mDc */
            data?: string;
          };
        };
      };
    };
  };
  'hash-verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          /** @description String to hash. */
          string: string;
          /** @description Hash you want to verify against. */
          hash: string;
        };
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example true */
            data?: boolean;
          };
        };
      };
    };
  };
  sort: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Collection identifier */
        collection: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          /** @description Primary key of item to move */
          item?: number;
          /** @description Primary key of item where to move the current item to */
          to?: number;
        };
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  import: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Collection identifier */
        collection: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file?: string;
        };
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  export: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Collection identifier */
        collection: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          /**
           * @description What file format to save the export to. One of csv, csv_utf8, xml, json, yaml
           * @enum {string}
           */
          format: 'csv' | 'csv_utf8' | 'xml' | 'json' | 'yaml';
          query: components['schemas']['Query'];
          file: components['schemas']['Files'];
        };
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  'clear-cache': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  random: {
    parameters: {
      query?: {
        /** @description Length of the random string. */
        length?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example 1>M3+4oh.S */
            data?: string;
          };
        };
      };
    };
  };
  readItemsDoraWorldContents: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description A limit on the number of objects that are returned. */
        limit?: components['parameters']['Limit'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
        /** @description How many items to skip when fetching data. */
        offset?: components['parameters']['Offset'];
        /** @description How to sort the returned items. `sort` is a CSV of fields used to sort the fetched items. Sorting defaults to ascending (ASC) order but a minus sign (` - `) can be used to reverse this to descending (DESC) order. Fields are prioritized by their order in the CSV. You can also use a ` ? ` to sort randomly. */
        sort?: components['parameters']['Sort'];
        /** @description Select items in collection by given conditions. */
        filter?: components['parameters']['Filter'];
        /** @description Filter by items that contain the given search query in one of their fields. */
        search?: components['parameters']['Search'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsDoraWorldContents'][];
            meta?: components['schemas']['x-metadata'];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
    };
  };
  createItemsDoraWorldContents: {
    parameters: {
      query?: {
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json':
          | components['schemas']['ItemsDoraWorldContents'][]
          | components['schemas']['ItemsDoraWorldContents'];
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsDoraWorldContents'][];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
    };
  };
  updateItemsDoraWorldContents: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description A limit on the number of objects that are returned. */
        limit?: components['parameters']['Limit'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
        /** @description How many items to skip when fetching data. */
        offset?: components['parameters']['Offset'];
        /** @description How to sort the returned items. `sort` is a CSV of fields used to sort the fetched items. Sorting defaults to ascending (ASC) order but a minus sign (` - `) can be used to reverse this to descending (DESC) order. Fields are prioritized by their order in the CSV. You can also use a ` ? ` to sort randomly. */
        sort?: components['parameters']['Sort'];
        /** @description Select items in collection by given conditions. */
        filter?: components['parameters']['Filter'];
        /** @description Filter by items that contain the given search query in one of their fields. */
        search?: components['parameters']['Search'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json':
          | components['schemas']['ItemsDoraWorldContents'][]
          | components['schemas']['ItemsDoraWorldContents'];
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsDoraWorldContents'][];
          };
        };
      };
    };
  };
  readSingleItemsDoraWorldContents: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
        /** @description Retrieve an item's state from a specific Content Version. The value corresponds to the "key" of the Content Version. */
        version?: components['parameters']['Version'];
      };
      header?: never;
      path: {
        /** @description Index of the item. */
        id: number | string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsDoraWorldContents'];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
      404: components['responses']['NotFoundError'];
    };
  };
  updateSingleItemsDoraWorldContents: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
      };
      header?: never;
      path: {
        /** @description Index of the item. */
        id: number | string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['ItemsDoraWorldContents'];
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsDoraWorldContents'];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
      404: components['responses']['NotFoundError'];
    };
  };
  readItemsLanguages: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description A limit on the number of objects that are returned. */
        limit?: components['parameters']['Limit'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
        /** @description How many items to skip when fetching data. */
        offset?: components['parameters']['Offset'];
        /** @description How to sort the returned items. `sort` is a CSV of fields used to sort the fetched items. Sorting defaults to ascending (ASC) order but a minus sign (` - `) can be used to reverse this to descending (DESC) order. Fields are prioritized by their order in the CSV. You can also use a ` ? ` to sort randomly. */
        sort?: components['parameters']['Sort'];
        /** @description Select items in collection by given conditions. */
        filter?: components['parameters']['Filter'];
        /** @description Filter by items that contain the given search query in one of their fields. */
        search?: components['parameters']['Search'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsLanguages'][];
            meta?: components['schemas']['x-metadata'];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
    };
  };
  createItemsLanguages: {
    parameters: {
      query?: {
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json':
          | components['schemas']['ItemsLanguages'][]
          | components['schemas']['ItemsLanguages'];
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsLanguages'][];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
    };
  };
  updateItemsLanguages: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description A limit on the number of objects that are returned. */
        limit?: components['parameters']['Limit'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
        /** @description How many items to skip when fetching data. */
        offset?: components['parameters']['Offset'];
        /** @description How to sort the returned items. `sort` is a CSV of fields used to sort the fetched items. Sorting defaults to ascending (ASC) order but a minus sign (` - `) can be used to reverse this to descending (DESC) order. Fields are prioritized by their order in the CSV. You can also use a ` ? ` to sort randomly. */
        sort?: components['parameters']['Sort'];
        /** @description Select items in collection by given conditions. */
        filter?: components['parameters']['Filter'];
        /** @description Filter by items that contain the given search query in one of their fields. */
        search?: components['parameters']['Search'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json':
          | components['schemas']['ItemsLanguages'][]
          | components['schemas']['ItemsLanguages'];
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsLanguages'][];
          };
        };
      };
    };
  };
  readSingleItemsLanguages: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
        /** @description Retrieve an item's state from a specific Content Version. The value corresponds to the "key" of the Content Version. */
        version?: components['parameters']['Version'];
      };
      header?: never;
      path: {
        /** @description Index of the item. */
        id: number | string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsLanguages'];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
      404: components['responses']['NotFoundError'];
    };
  };
  updateSingleItemsLanguages: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
      };
      header?: never;
      path: {
        /** @description Index of the item. */
        id: number | string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['ItemsLanguages'];
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsLanguages'];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
      404: components['responses']['NotFoundError'];
    };
  };
  readItemsDoraWorldContentsTranslations: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description A limit on the number of objects that are returned. */
        limit?: components['parameters']['Limit'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
        /** @description How many items to skip when fetching data. */
        offset?: components['parameters']['Offset'];
        /** @description How to sort the returned items. `sort` is a CSV of fields used to sort the fetched items. Sorting defaults to ascending (ASC) order but a minus sign (` - `) can be used to reverse this to descending (DESC) order. Fields are prioritized by their order in the CSV. You can also use a ` ? ` to sort randomly. */
        sort?: components['parameters']['Sort'];
        /** @description Select items in collection by given conditions. */
        filter?: components['parameters']['Filter'];
        /** @description Filter by items that contain the given search query in one of their fields. */
        search?: components['parameters']['Search'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsDoraWorldContentsTranslations'][];
            meta?: components['schemas']['x-metadata'];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
    };
  };
  createItemsDoraWorldContentsTranslations: {
    parameters: {
      query?: {
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json':
          | components['schemas']['ItemsDoraWorldContentsTranslations'][]
          | components['schemas']['ItemsDoraWorldContentsTranslations'];
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsDoraWorldContentsTranslations'][];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
    };
  };
  updateItemsDoraWorldContentsTranslations: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description A limit on the number of objects that are returned. */
        limit?: components['parameters']['Limit'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
        /** @description How many items to skip when fetching data. */
        offset?: components['parameters']['Offset'];
        /** @description How to sort the returned items. `sort` is a CSV of fields used to sort the fetched items. Sorting defaults to ascending (ASC) order but a minus sign (` - `) can be used to reverse this to descending (DESC) order. Fields are prioritized by their order in the CSV. You can also use a ` ? ` to sort randomly. */
        sort?: components['parameters']['Sort'];
        /** @description Select items in collection by given conditions. */
        filter?: components['parameters']['Filter'];
        /** @description Filter by items that contain the given search query in one of their fields. */
        search?: components['parameters']['Search'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json':
          | components['schemas']['ItemsDoraWorldContentsTranslations'][]
          | components['schemas']['ItemsDoraWorldContentsTranslations'];
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsDoraWorldContentsTranslations'][];
          };
        };
      };
    };
  };
  readSingleItemsDoraWorldContentsTranslations: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
        /** @description Retrieve an item's state from a specific Content Version. The value corresponds to the "key" of the Content Version. */
        version?: components['parameters']['Version'];
      };
      header?: never;
      path: {
        /** @description Index of the item. */
        id: number | string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsDoraWorldContentsTranslations'];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
      404: components['responses']['NotFoundError'];
    };
  };
  updateSingleItemsDoraWorldContentsTranslations: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
      };
      header?: never;
      path: {
        /** @description Index of the item. */
        id: number | string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['ItemsDoraWorldContentsTranslations'];
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsDoraWorldContentsTranslations'];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
      404: components['responses']['NotFoundError'];
    };
  };
  readItemsFujikoMuseumContents: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description A limit on the number of objects that are returned. */
        limit?: components['parameters']['Limit'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
        /** @description How many items to skip when fetching data. */
        offset?: components['parameters']['Offset'];
        /** @description How to sort the returned items. `sort` is a CSV of fields used to sort the fetched items. Sorting defaults to ascending (ASC) order but a minus sign (` - `) can be used to reverse this to descending (DESC) order. Fields are prioritized by their order in the CSV. You can also use a ` ? ` to sort randomly. */
        sort?: components['parameters']['Sort'];
        /** @description Select items in collection by given conditions. */
        filter?: components['parameters']['Filter'];
        /** @description Filter by items that contain the given search query in one of their fields. */
        search?: components['parameters']['Search'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsFujikoMuseumContents'][];
            meta?: components['schemas']['x-metadata'];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
    };
  };
  createItemsFujikoMuseumContents: {
    parameters: {
      query?: {
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json':
          | components['schemas']['ItemsFujikoMuseumContents'][]
          | components['schemas']['ItemsFujikoMuseumContents'];
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsFujikoMuseumContents'][];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
    };
  };
  updateItemsFujikoMuseumContents: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description A limit on the number of objects that are returned. */
        limit?: components['parameters']['Limit'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
        /** @description How many items to skip when fetching data. */
        offset?: components['parameters']['Offset'];
        /** @description How to sort the returned items. `sort` is a CSV of fields used to sort the fetched items. Sorting defaults to ascending (ASC) order but a minus sign (` - `) can be used to reverse this to descending (DESC) order. Fields are prioritized by their order in the CSV. You can also use a ` ? ` to sort randomly. */
        sort?: components['parameters']['Sort'];
        /** @description Select items in collection by given conditions. */
        filter?: components['parameters']['Filter'];
        /** @description Filter by items that contain the given search query in one of their fields. */
        search?: components['parameters']['Search'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json':
          | components['schemas']['ItemsFujikoMuseumContents'][]
          | components['schemas']['ItemsFujikoMuseumContents'];
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsFujikoMuseumContents'][];
          };
        };
      };
    };
  };
  readSingleItemsFujikoMuseumContents: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
        /** @description Retrieve an item's state from a specific Content Version. The value corresponds to the "key" of the Content Version. */
        version?: components['parameters']['Version'];
      };
      header?: never;
      path: {
        /** @description Index of the item. */
        id: number | string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsFujikoMuseumContents'];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
      404: components['responses']['NotFoundError'];
    };
  };
  updateSingleItemsFujikoMuseumContents: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
      };
      header?: never;
      path: {
        /** @description Index of the item. */
        id: number | string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['ItemsFujikoMuseumContents'];
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsFujikoMuseumContents'];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
      404: components['responses']['NotFoundError'];
    };
  };
  readItemsFujikoMuseumContentsTranslations: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description A limit on the number of objects that are returned. */
        limit?: components['parameters']['Limit'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
        /** @description How many items to skip when fetching data. */
        offset?: components['parameters']['Offset'];
        /** @description How to sort the returned items. `sort` is a CSV of fields used to sort the fetched items. Sorting defaults to ascending (ASC) order but a minus sign (` - `) can be used to reverse this to descending (DESC) order. Fields are prioritized by their order in the CSV. You can also use a ` ? ` to sort randomly. */
        sort?: components['parameters']['Sort'];
        /** @description Select items in collection by given conditions. */
        filter?: components['parameters']['Filter'];
        /** @description Filter by items that contain the given search query in one of their fields. */
        search?: components['parameters']['Search'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsFujikoMuseumContentsTranslations'][];
            meta?: components['schemas']['x-metadata'];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
    };
  };
  createItemsFujikoMuseumContentsTranslations: {
    parameters: {
      query?: {
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json':
          | components['schemas']['ItemsFujikoMuseumContentsTranslations'][]
          | components['schemas']['ItemsFujikoMuseumContentsTranslations'];
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsFujikoMuseumContentsTranslations'][];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
    };
  };
  updateItemsFujikoMuseumContentsTranslations: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description A limit on the number of objects that are returned. */
        limit?: components['parameters']['Limit'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
        /** @description How many items to skip when fetching data. */
        offset?: components['parameters']['Offset'];
        /** @description How to sort the returned items. `sort` is a CSV of fields used to sort the fetched items. Sorting defaults to ascending (ASC) order but a minus sign (` - `) can be used to reverse this to descending (DESC) order. Fields are prioritized by their order in the CSV. You can also use a ` ? ` to sort randomly. */
        sort?: components['parameters']['Sort'];
        /** @description Select items in collection by given conditions. */
        filter?: components['parameters']['Filter'];
        /** @description Filter by items that contain the given search query in one of their fields. */
        search?: components['parameters']['Search'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json':
          | components['schemas']['ItemsFujikoMuseumContentsTranslations'][]
          | components['schemas']['ItemsFujikoMuseumContentsTranslations'];
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsFujikoMuseumContentsTranslations'][];
          };
        };
      };
    };
  };
  readSingleItemsFujikoMuseumContentsTranslations: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
        /** @description Retrieve an item's state from a specific Content Version. The value corresponds to the "key" of the Content Version. */
        version?: components['parameters']['Version'];
      };
      header?: never;
      path: {
        /** @description Index of the item. */
        id: number | string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsFujikoMuseumContentsTranslations'];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
      404: components['responses']['NotFoundError'];
    };
  };
  updateSingleItemsFujikoMuseumContentsTranslations: {
    parameters: {
      query?: {
        /** @description Control what fields are being returned in the object. */
        fields?: components['parameters']['Fields'];
        /** @description What metadata to return in the response. */
        meta?: components['parameters']['Meta'];
      };
      header?: never;
      path: {
        /** @description Index of the item. */
        id: number | string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['ItemsFujikoMuseumContentsTranslations'];
      };
    };
    responses: {
      /** @description Successful request */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['ItemsFujikoMuseumContentsTranslations'];
          };
        };
      };
      401: components['responses']['UnauthorizedError'];
      404: components['responses']['NotFoundError'];
    };
  };
}
